# Generated by Django 5.1.1 on 2024-11-13 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_shippingaddress_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shippingaddress',
            name='unique_customer_order',
        ),
        migrations.AlterUniqueTogether(
            name='shippingaddress',
            unique_together={('customer', 'order')},
        ),
    ]
