# Generated by Django 5.1.1 on 2024-11-13 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
