# Generated by Django 5.1.1 on 2024-11-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.ManyToManyField(related_name='product', to='app.category'),
        ),
    ]
